name: C Coding Style Check

# Runs on pushes to pull request
on: pull_request

jobs:
  # Build job
  clang-format-style-check:
    name: C Coding Style Check (clang-format check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19
          sudo apt install clang-format-19
      - name: clang-format code formatting check
        run: clang-format-19 --dry-run -Werror *.c *.h
